### ISSUE TITLE
Contradiction

### ISSUE THREAD

**Issue by DigiG0d** [austinhuang0131/austinhuang0131#5]
If Bainsta is no longer functioning as a result of the Cease and Desist notice, how is Frost for Facebook still live and working? It essentially does the same thing that letter was complaining about in regards to Barinsta. 

So Barinsta needs to stop, but other apps that do the same thing is perfectly fine?

 I'm not buying the legitimacy of that letter. Every time I try to call that attorney listed on that document I get a voice-mail. What attorney (solicitor if you're in the UK) doesn't answer their phone? I'm not buying it.

**Comment by austinhuang0131** [comment]
> If Bainsta is no longer functioning

false, they wouldn't need to do this if it can just simply stop functioning

> I'm not buying the legitimacy of that letter.

tbf i did lose my facebook & instagram accounts just before receiving this, so i will not question the legitimacy of the letter itself (this does not imply anything on the contents of the letter)

> Every time I try to call that attorney listed on that document I get a voice-mail.

it is my understanding that perkies & coie sends these letters on a daily basis so i will not be surprised if it's literally automated, but please don't intimidate the attorney

no i'm not in the uk, why does EVERYONE think i live in the uk
